const express=require('express')
const userRegisterContoller = require('../app/controllers/userRegisterController')
const Authenticate = require('../app/middleware/authenticate')
const movieController = require('../app/controllers/movieControllers')
const seatController=require('../app/controllers/seatController')
const upload = require('../app/middleware/multerConfig')
const router=express.Router()

router.post("/registerUser",   userRegisterContoller.create)
router.post('/login',userRegisterContoller.login)
router.get('/getAllUsers',userRegisterContoller.getUsers)
router.post('/addMovie',Authenticate,upload.single('image') , movieController.addMovie)
router.delete('/deleteMovie/:id',Authenticate,movieController.deleteMovie)
router.put('/bookMovie/:id',Authenticate,movieController.bookMovie)
router.post('/bookSeat',Authenticate,seatController.bookSeat)
router.get('/getSeats',Authenticate,seatController.getSeats)
router.get('/getMovies',Authenticate,movieController.getMovies)
router.post('/profile',Authenticate,userRegisterContoller.profile)
router.post('/payment',Authenticate,    seatController.payment)
router.get('/success',seatController.success)
router.get('/getBooking',seatController.getBooking)
module.exports=router